---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Delete the default route for public network
      ansible.builtin.command: ip route del default dev eth0

    - name: "Configure BaseOS repository for RHEL 8"
      ansible.builtin.yum_repository:
        name: rhel8-baseos
        baseurl: http://192.168.56.78/repos/rhel-8-for-x86_64-baseos-rpms
        enabled: yes
        gpgcheck: no
        description: "BaseOS repo for RHEL 8"

    - name: "Configure AppStream repository for RHEL 8"
      ansible.builtin.yum_repository:
        name: rhel8-apps
        baseurl: http://192.168.56.78/repos/rhel-8-for-x86_64-appstream-rpms
        enabled: yes
        gpgcheck: no
        description: "AppStream repo for RHEL 8"
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
    
    - name: Ensure all repositories are cleaned and refreshed
      ansible.builtin.command: yum clean all
