---
- hosts: "namespace_{{ vm_name }}"
  gather_facts: yes
  tasks:
#    - name: Delete the default route for public network
#      ansible.builtin.command: ip route del default dev eth0

    - name: "Configure BaseOS repository for RHEL 9"
      ansible.builtin.yum_repository:
        name: rhel9-baseos
        baseurl: http://10.66.208.72/repos/rhel-9-for-x86_64-baseos-rpms
        enabled: yes
        gpgcheck: no
        description: "BaseOS repo for RHEL 9"

    - name: "Configure AppStream repository for RHEL 9"
      ansible.builtin.yum_repository:
        name: rhel9-apps
        baseurl: http://10.66.208.72/repos/rhel-9-for-x86_64-appstream-rpms
        enabled: yes
        gpgcheck: no
        description: "AppStream repo for RHEL 9"
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
    
    - name: Ensure all repositories are cleaned and refreshed
      ansible.builtin.command: yum clean all
