---
- hosts: all
  gather_facts: yes
  tasks:
    - name: "Configure BaseOS repository for RHEL 9"
      ansible.builtin.yum_repository:
        name: rhel9-baseos
        baseurl: http://10.66.208.72/repos/rhel-9-for-x86_64-baseos-rpms
        enabled: yes
        gpgcheck: no
        description: "BaseOS repo for RHEL 9"

    - name: "Configure AppStream repository for RHEL 9"
      ansible.builtin.yum_repository:
        name: rhel9-apps
        baseurl: http://10.66.208.72/repos/rhel-9-for-x86_64-appstream-rpms
        enabled: yes
        gpgcheck: no
        description: "AppStream repo for RHEL 9"
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9"
    
    - name: Disable IPV6 setting 
      ansible.builtin.command: nmcli connection modify "System eth0" ipv6.method "disabled"

    - name: Restart connection 
      ansible.builtin.command: nmcli connection up "System eth0"

    - name: Ensure all repositories are cleaned and refreshed
      ansible.builtin.command: yum clean all
