- name: Create a project
  hosts: localhost

  tasks:
    - name: Create Project
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: aap
            labels:
              kubernetes.io/metadata.name: aap
