---
- hosts: all
  gather_facts: yes
  tasks:
    - name: List available updates
      ansible.builtin.command: yum updateinfo list updates
      register: myresult

    - name: Print available updates
      debug:
        var:  myresult.stdout_lines
