apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "{{ vm_name }}-disk-3"
  namespace: "{{ vm_namespace }}"
spec:
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: "{{ vm_newstorage }}"
