apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel8-vm-01
  namespace: wm-test2
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: rhel8-vm-01
    spec:
      source:
        pvc:
          name: rhel8.10-gold-image-odf
          namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: rhel8-vm-01
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: nic1
          - bridge: {}
            model: virtio
            name: nic2
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
      - multus:
          networkName: default/public-network-continental-alpaca
        name: nic1
      - multus:
          networkName: default/public-network-continental-alpaca
        name: nic2
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: rhel8-vm-01
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            password: 'redhat123'
            chpasswd: { expire: False }
        name: cloudinitdisk
